### PR TITLE
Added 2 more tests, 1 failing

### PR DESCRIPTION
**Pull request by SteveEdson**
The final test is currently failing however. See issue #9

### CODE REVIEW

**Comment by SteveEdson** [comment]
Any idea why this would be failing on my machine?

**Comment by bjeavons** [comment]
What version of PHP are you using?

**Comment by SteveEdson** [comment]
Ahhhh I've figured it out. Packagist is recommending version 0.1.3, which is what I was using. This is failing for my tests.

The latest `dev-master` seems to be working correctly. Would it be possible to release a new version, so that I can use the fixes without being on the dev releases please?

Thanks.

**Comment by bjeavons** [comment]
Yes, you're running into what https://github.com/bjeavons/zxcvbn-php/commit/dc8aa91cf16a52d0138a9ec6f3abdfc6a7e93ae1 fixes

https://github.com/bjeavons/zxcvbn-php/releases/tag/0.1.4

**Pull request closed without merging**
