### PR TITLE
Exactly match upstream dropbox library's functionality and algorithms

### PR DESCRIPTION
**Pull request by mkopinsky**
Addresses #15

### CODE REVIEW

**Comment by timwsuqld** [comment]
Any progress on getting this merged in?

**Comment by mkopinsky** [comment]
This PR has now been open for 6 weeks, and active work on the branch has been going on since March. I've gone ahead and published my fork on packagist - https://packagist.org/packages/mkopinsky/zxcvbn-php

**Comment by peter279k** [comment]
Actually, thse commits in this PR are very huge.

It should clear them and I don't think other people commits should include in this PR :).

**Comment by mkopinsky** [comment]
The amount of changes indeed is huge, but that's what was necessary to exactly match the upstream js library.

**Comment by peter279k** [comment]
Hi @mkopinsky, thank you for your reply.

I think this PR should be cleaned up the commits and squashed all commits to one commit.

In general, the repository owner doesn't want to merge a PR with the large commits :-).

**Comment by mkopinsky** [comment]
The issue with this PR (in my mind) isn't the number of commits but the number of changes. If @bjeavons says that he'd prefer me to squash commits, I'd be happy to do so.

**Comment by peter279k** [comment]
Hi @mkopinsky.

Ok. Thank you for answer and just wait for the repository author.

**Comment by Hate9** [comment]
Hey, can @bjeavons please take a look and answer? I'm using the library and I'd really like to be able to update my app so that the PHP side matches the JS.

**Comment by mkopinsky** [comment]
@bjeavons has indicated that he doesn't intend on merging this.

If you want your PHP side to match the JS, switch to mkopinsky/zxcvbn-php in your composer.json

**Comment by Hate9** [comment]
@mkopinsky It's a shame that he didn't want to merge it, but I'm glad I can just update to your repo.
Any idea why he didn't want to merge the PR?

**Comment by mkopinsky** [comment]
https://github.com/bjeavons/zxcvbn-php/issues/15#issuecomment-377952148

**Pull request merged**
